site_name: "robot-markdown"
site_description: "Convert RobotFramework output XML to markdown"
site_url: "https://chme.github.io/python-robot-markdown"
repo_url: "https://github.com/chme/python-robot-markdown"
repo_name: "chme/python-robot-markdown"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/robot_markdown]
copyright: Copyright &copy; 2023 Christian Meffert
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Examples:
  - Robot Demo: examples/Robot_Demo/suite.md
  - Robot Language: examples/Robot_Language/suite.md
  - Output Files: examples/Output_Files/
# defer to gen-files + literate-nav
- API reference:
  - robot-markdown: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/material.css
- css/mkdocstrings.css
- css/robotmarkdown.css

markdown_extensions:
- attr_list
- admonition
- callouts
- def_list
- footnotes
- md_in_html
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: true

plugins:
- search
- robot_markdown:
    reports:
    - robot_reports_dir: examples/Robot_Demo/output
      robot_output_xml: output.xml
      docs_rel_dir: examples/Robot_Demo
      docs_md_file: suite.md
      overwrite_cached_files: true
      cache_dir: .cache
    - robot_reports_dir: examples/Robot_Language/output
      robot_output_xml: output.xml
      docs_rel_dir: examples/Robot_Language
      docs_md_file: suite.md
      overwrite_cached_files: true
      cache_dir: .cache
    - robot_reports_dir: examples/Output_Files/output
      robot_output_xml: output.xml
      create_summary_md: true
      summary_md_file: SUMMARY.md
      docs_rel_dir: examples/Output_Files
      docs_md_file: suite.md
      overwrite_cached_files: true
      cache_dir: .cache
      copy_files: true
      env_file: test.env
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [src]
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
- git-committers:
    enabled: !ENV [DEPLOY, false]
    repository: chme/python-robot-markdown
- minify:
    minify_html: !ENV [DEPLOY, false]
- group:
    enabled: !ENV [MATERIAL_INSIDERS, false]
    plugins:
    - typeset

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/chme
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/python-robot-markdown/community
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/robot-markdown/
